# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [4]:
import numpy as np
numpay_array=np.arange(1,11)
print(numpay_array)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [7]:
zero_3x3=np.zeros((3,3))
zero_3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [10]:
evenly_spaced=np.linspace(0,5,10)
evenly_spaced

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [13]:
identity_m=np.ones((5,5))
identity_m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [16]:
identity_m=np.matrix(np.random.random(16)).reshape((4,4))
identity_m

matrix([[0.41070786, 0.58136587, 0.76991612, 0.98424385],
        [0.92373384, 0.50366157, 0.35691868, 0.63621006],
        [0.84089495, 0.17421853, 0.96673302, 0.22976545],
        [0.11021891, 0.72737658, 0.13693155, 0.56260988]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [19]:
board=np.random.randint(12,16,20)
board.shape

(20,)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [22]:
ft=np.random.random(16)
ft=ft.reshape(4,4)
ft

array([[0.82479206, 0.67735271, 0.41392929, 0.85909369],
       [0.55167634, 0.21920051, 0.03725813, 0.42215808],
       [0.7104336 , 0.12357067, 0.94073379, 0.36176669],
       [0.2853648 , 0.7490746 , 0.24207229, 0.97878512]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [25]:
ft.ctypes

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [28]:
integersInterger=np.arange(1,101)
integersInterger[integersInterger%2==0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [31]:
mat_m=np.random.randint(10,50,size=(6,6))
mat_m

array([[30, 12, 41, 47, 46, 47],
       [15, 14, 29, 47, 14, 23],
       [44, 29, 17, 46, 19, 12],
       [48, 11, 26, 15, 36, 45],
       [37, 43, 37, 34, 15, 23],
       [34, 39, 29, 15, 19, 24]])

In [32]:
np.random.randint(5, size=(2, 4))

array([[3, 3, 1, 3],
       [2, 3, 0, 1]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [34]:
M1=mat_m[:3,:3]
print("M1 = ",M1)
M2=mat_m[3:,3:]
print("M1 = ",M2)

M1 =  [[30 12 41]
 [15 14 29]
 [44 29 17]]
M1 =  [[15 36 45]
 [34 15 23]
 [15 19 24]]


### 

Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [38]:
sum_array=integersInterger.sum()
sum_array

5050

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [41]:
# This is for 1D
mean_array=integersInterger.mean()
print("The mean is ",mean_array)
std_array=integersInterger.std()
print("The mean is ",std_array)
medium_array=np.median(integersInterger)
print("The mean is ",medium_array)

The mean is  50.5
The mean is  28.86607004772212
The mean is  50.5


In [42]:
#let us look at 2D
mean_arrayc=np.mean(mat_m,axis=1)
print("The mean on columns are ",mean_arrayc)
mean_arrayr=np.mean(mat_m,axis=0)
print("The mean of each row are ",mean_arrayr)
std_arrayr=np.std(mat_m,axis=1)
std_arrayc=np.std(mat_m,axis=0)
print("The r std are ",std_arrayr)
print("The c td are ",std_arrayc)

median_arrayr=np.median(mat_m,axis=1)
median_arrayc=np.median(mat_m,axis=0)
print("The r median are ",median_arrayr)
print("The c median are ",median_arrayc)


The mean on columns are  [37.16666667 23.66666667 27.83333333 30.16666667 31.5        26.66666667]
The mean of each row are  [34.66666667 24.66666667 29.83333333 34.         24.83333333 29.        ]
The r std are  [12.72028127 11.79924668 13.15822514 14.0643363   9.51752769  8.29993307]
The c td are  [10.64059313 13.04692386  7.71182353 14.16568624 11.93617285 12.68857754]
The r median are  [43.5 19.  24.  31.  35.5 26.5]
The c median are  [35.5 21.5 29.  40.  19.  23.5]


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [45]:
# This is for 1D
max=integersInterger.max()
print("The max is ",max)
min=integersInterger.min()
print("The min is ",min)


The max is  100
The min is  1


In [46]:
#let us look at 2D
max_arrayc=np.max(mat_m,axis=1)
print("The max on columns are ",mean_arrayc)
max_arrayr=np.max(mat_m,axis=0)
print("The max of each row are ",mean_arrayr)


max_arrayc=np.min(mat_m,axis=1)
print("The min on columns are ",mean_arrayc)
max_arrayr=np.min(mat_m,axis=0)
print("The min of each row are ",mean_arrayr)

The max on columns are  [37.16666667 23.66666667 27.83333333 30.16666667 31.5        26.66666667]
The max of each row are  [34.66666667 24.66666667 29.83333333 34.         24.83333333 29.        ]
The min on columns are  [37.16666667 23.66666667 27.83333333 30.16666667 31.5        26.66666667]
The min of each row are  [34.66666667 24.66666667 29.83333333 34.         24.83333333 29.        ]


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [49]:
rand_intenger=np.random.randint(5,20,30)
rand_intenger

array([10, 12, 18, 14,  7,  5,  8,  6, 17, 15, 15, 15, 16, 19, 14,  7, 10,
       19, 15,  8,  8, 19, 14, 17, 14,  9, 10, 19,  5,  9])

In [50]:
np.argmax(rand_intenger)

13

In [51]:
np.argmin(rand_intenger)

5

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [53]:
print(rand_intenger)
print(rand_intenger[::-1])
np.flip(rand_intenger,axis=0)

[10 12 18 14  7  5  8  6 17 15 15 15 16 19 14  7 10 19 15  8  8 19 14 17
 14  9 10 19  5  9]
[ 9  5 19 10  9 14 17 14 19  8  8 15 19 10  7 14 19 16 15 15 15 17  6  8
  5  7 14 18 12 10]


array([ 9,  5, 19, 10,  9, 14, 17, 14, 19,  8,  8, 15, 19, 10,  7, 14, 19,
       16, 15, 15, 15, 17,  6,  8,  5,  7, 14, 18, 12, 10])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [56]:
mat_m3x31=np.random.randint(1,5,size=(3,3))
mat_m3x32=np.random.randint(1,5,size=(3,3))

In [57]:
print(mat_m3x31)
print(mat_m3x32)

[[1 3 4]
 [2 4 2]
 [3 1 4]]
[[2 4 2]
 [1 3 4]
 [1 2 2]]


In [58]:
mat_m3x31*mat_m3x32

array([[ 2, 12,  8],
       [ 2, 12,  8],
       [ 3,  2,  8]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [60]:
hjk=np.arange(1, 9)
print(hjk)
diagonal=np.diag(hjk)
diagonal

[1 2 3 4 5 6 7 8]


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [63]:
print(np.dot(mat_m3x31,mat_m3x32))


[[ 9 21 22]
 [10 24 24]
 [11 23 18]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [66]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [68]:
np.vstack((mat_m3x32,mat_m3x31))

array([[2, 4, 2],
       [1, 3, 4],
       [1, 2, 2],
       [1, 3, 4],
       [2, 4, 2],
       [3, 1, 4]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [70]:
np.hstack((mat_m3x32,mat_m3x31))


array([[2, 4, 2, 1, 3, 4],
       [1, 3, 4, 2, 4, 2],
       [1, 2, 2, 3, 1, 4]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [107]:
mat_m3x32

array([[2, 4, 2],
       [1, 3, 4],
       [1, 2, 2]])

In [115]:

np.split(mat_m3x32,3)

[array([[2, 4, 2]]), array([[1, 3, 4]]), array([[1, 2, 2]])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [137]:
new_tab=np.random.randn(12)
np.round(new_tab,2) 

array([-1.15,  0.52, -0.73,  0.82, -1.16, -0.07,  1.44,  1.15, -0.66,
        2.09, -0.44, -0.14])

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [142]:
uniqu=np.unique(new_tab)
uniqu

array([-1.16366769, -1.15190215, -0.73465874, -0.66206958, -0.442646  ,
       -0.13939575, -0.06780034,  0.51512571,  0.82294856,  1.15369162,
        1.44052228,  2.08561193])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [147]:
new_tab[new_tab<=1]=8
new_tab

array([8.        , 8.        , 8.        , 8.        , 8.        ,
       8.        , 1.44052228, 1.15369162, 8.        , 2.08561193,
       8.        , 8.        ])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [149]:
np.sum(new_tab)

76.67982583210737

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [155]:
np.count_nonzero(new_tab)

12

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [157]:
np.sort(new_tab)

array([1.15369162, 1.44052228, 2.08561193, 8.        , 8.        ,
       8.        , 8.        , 8.        , 8.        , 8.        ,
       8.        , 8.        ])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [163]:
print(np.sum(mat_m3x32,axis=0))
print(np.sum(mat_m3x32,axis=1))

[4 9 8]
[8 8 5]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [166]:
# Generate a 3x3 random 2D array
random_matrix = np.random.rand(3, 3)

# Normalize the array (scaling values between 0 and 1)
min_val = np.min(random_matrix)
max_val = np.max(random_matrix)
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)

print("Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[0.85896501 0.52975845 0.85422099]
 [0.15532459 0.86638386 0.99402977]
 [0.79625611 0.31574069 0.90861569]]

Normalized Matrix:
[[0.83896039 0.44644277 0.83330402]
 [0.         0.84780598 1.        ]
 [0.76419168 0.19126638 0.89815959]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [168]:
print(np.dot(mat_m3x32,mat_m3x31))

[[16 24 24]
 [19 19 26]
 [11 13 16]]


### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace_value = np.trace(matrix)
print("Trace of the matrix:", trace_value)

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [173]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Swap row 0 and row 2
matrix[[0, 2]] = matrix[[2, 0]]

print("Matrix after swapping rows 0 and 2:")
print(matrix)


Matrix after swapping rows 0 and 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [176]:
array_1d = np.array([1, 2, 3, 4, 5])

column_vector = array_1d.reshape(-1, 1)
print("Column vector:")
print(column_vector)


Column vector:
[[1]
 [2]
 [3]
 [4]
 [5]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [181]:
determinant = np.linalg.det(mat_m3x32)
print("Determinant of the matrix:", determinant)


Determinant of the matrix: 2.0


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

In [183]:
eigenvalues, eigenvectors = np.linalg.eig(mat_m3x32)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues: [6.74752291+0.j         0.12623854+0.52959315j 0.12623854-0.52959315j]
Eigenvectors:
[[ 0.68315567+0.j          0.84592281+0.j          0.84592281-0.j        ]
 [ 0.61032016+0.j         -0.43073701+0.21928461j -0.43073701-0.21928461j]
 [ 0.40100828+0.j          0.06894525-0.21457176j  0.06894525+0.21457176j]]


### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [185]:
A = np.array([[3, 2],
              [1, 2]])

# Constant vector b
b = np.array([5, 5])

# Solving for x
solution = np.linalg.solve(A, b)
print("Solution of the system of equations:", solution)


Solution of the system of equations: [0.  2.5]


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [187]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal_elements = np.diag(matrix)
print("Diagonal elements of the matrix:")
print(diagonal_elements)


Diagonal elements of the matrix:
[ 1  6 11 16]


### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---